// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: vmp.proto

package vmp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*Request_Ping
	//	*Request_HostInfo
	//	*Request_Exec
	//	*Request_UploadStart
	//	*Request_UploadChunk
	//	*Request_UploadFinish
	Command       isRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_vmp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_vmp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_vmp_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetCommand() isRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Request) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Request) GetHostInfo() *HostInfoRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_HostInfo); ok {
			return x.HostInfo
		}
	}
	return nil
}

func (x *Request) GetExec() *ExecRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *Request) GetUploadStart() *UploadStartRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_UploadStart); ok {
			return x.UploadStart
		}
	}
	return nil
}

func (x *Request) GetUploadChunk() *UploadChunkRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_UploadChunk); ok {
			return x.UploadChunk
		}
	}
	return nil
}

func (x *Request) GetUploadFinish() *UploadFinishRequest {
	if x != nil {
		if x, ok := x.Command.(*Request_UploadFinish); ok {
			return x.UploadFinish
		}
	}
	return nil
}

type isRequest_Command interface {
	isRequest_Command()
}

type Request_Ping struct {
	Ping *PingRequest `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type Request_HostInfo struct {
	HostInfo *HostInfoRequest `protobuf:"bytes,3,opt,name=host_info,json=hostInfo,proto3,oneof"`
}

type Request_Exec struct {
	Exec *ExecRequest `protobuf:"bytes,4,opt,name=exec,proto3,oneof"`
}

type Request_UploadStart struct {
	UploadStart *UploadStartRequest `protobuf:"bytes,5,opt,name=upload_start,json=uploadStart,proto3,oneof"`
}

type Request_UploadChunk struct {
	UploadChunk *UploadChunkRequest `protobuf:"bytes,6,opt,name=upload_chunk,json=uploadChunk,proto3,oneof"`
}

type Request_UploadFinish struct {
	UploadFinish *UploadFinishRequest `protobuf:"bytes,7,opt,name=upload_finish,json=uploadFinish,proto3,oneof"`
}

func (*Request_Ping) isRequest_Command() {}

func (*Request_HostInfo) isRequest_Command() {}

func (*Request_Exec) isRequest_Command() {}

func (*Request_UploadStart) isRequest_Command() {}

func (*Request_UploadChunk) isRequest_Command() {}

func (*Request_UploadFinish) isRequest_Command() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*Response_Ping
	//	*Response_HostInfo
	//	*Response_Exec
	//	*Response_Upload
	Result        isResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_vmp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_vmp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_vmp_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetResult() isResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Response) GetPing() *PingResponse {
	if x != nil {
		if x, ok := x.Result.(*Response_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Response) GetHostInfo() *HostInfoResponse {
	if x != nil {
		if x, ok := x.Result.(*Response_HostInfo); ok {
			return x.HostInfo
		}
	}
	return nil
}

func (x *Response) GetExec() *ExecResponse {
	if x != nil {
		if x, ok := x.Result.(*Response_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *Response) GetUpload() *UploadResponse {
	if x != nil {
		if x, ok := x.Result.(*Response_Upload); ok {
			return x.Upload
		}
	}
	return nil
}

type isResponse_Result interface {
	isResponse_Result()
}

type Response_Ping struct {
	Ping *PingResponse `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type Response_HostInfo struct {
	HostInfo *HostInfoResponse `protobuf:"bytes,4,opt,name=host_info,json=hostInfo,proto3,oneof"`
}

type Response_Exec struct {
	Exec *ExecResponse `protobuf:"bytes,5,opt,name=exec,proto3,oneof"`
}

type Response_Upload struct {
	Upload *UploadResponse `protobuf:"bytes,6,opt,name=upload,proto3,oneof"`
}

func (*Response_Ping) isResponse_Result() {}

func (*Response_HostInfo) isResponse_Result() {}

func (*Response_Exec) isResponse_Result() {}

func (*Response_Upload) isResponse_Result() {}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_vmp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_vmp_proto_rawDescGZIP(), []int{2}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_vmp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_vmp_proto_rawDescGZIP(), []int{3}
}

type HostInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfoRequest) Reset() {
	*x = HostInfoRequest{}
	mi := &file_vmp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoRequest) ProtoMessage() {}

func (x *HostInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoRequest.ProtoReflect.Descriptor instead.
func (*HostInfoRequest) Descriptor() ([]byte, []int) {
	return file_vmp_proto_rawDescGZIP(), []int{4}
}

type HostInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfoResponse) Reset() {
	*x = HostInfoResponse{}
	mi := &file_vmp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoResponse) ProtoMessage() {}

func (x *HostInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoResponse.ProtoReflect.Descriptor instead.
func (*HostInfoResponse) Descriptor() ([]byte, []int) {
	return file_vmp_proto_rawDescGZIP(), []int{5}
}

func (x *HostInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HostInfoResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Arguments      []string               `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Username       string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Detach         bool                   `protobuf:"varint,5,opt,name=detach,proto3" json:"detach,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_vmp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_vmp_proto_rawDescGZIP(), []int{6}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ExecRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ExecRequest) GetDetach() bool {
	if x != nil {
		return x.Detach
	}
	return false
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	TimedOut      bool                   `protobuf:"varint,4,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_vmp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_vmp_proto_rawDescGZIP(), []int{7}
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *ExecResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type UploadStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStartRequest) Reset() {
	*x = UploadStartRequest{}
	mi := &file_vmp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStartRequest) ProtoMessage() {}

func (x *UploadStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStartRequest.ProtoReflect.Descriptor instead.
func (*UploadStartRequest) Descriptor() ([]byte, []int) {
	return file_vmp_proto_rawDescGZIP(), []int{8}
}

func (x *UploadStartRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadStartRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *UploadStartRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadStartRequest) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

type UploadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkRequest) Reset() {
	*x = UploadChunkRequest{}
	mi := &file_vmp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkRequest) ProtoMessage() {}

func (x *UploadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkRequest.ProtoReflect.Descriptor instead.
func (*UploadChunkRequest) Descriptor() ([]byte, []int) {
	return file_vmp_proto_rawDescGZIP(), []int{9}
}

func (x *UploadChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadFinishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFinishRequest) Reset() {
	*x = UploadFinishRequest{}
	mi := &file_vmp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFinishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFinishRequest) ProtoMessage() {}

func (x *UploadFinishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFinishRequest.ProtoReflect.Descriptor instead.
func (*UploadFinishRequest) Descriptor() ([]byte, []int) {
	return file_vmp_proto_rawDescGZIP(), []int{10}
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  uint64                 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_vmp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_vmp_proto_rawDescGZIP(), []int{11}
}

func (x *UploadResponse) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

var File_vmp_proto protoreflect.FileDescriptor

const file_vmp_proto_rawDesc = "" +
	"\n" +
	"\tvmp.proto\x12\x03vmp\"\xe6\x02\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12&\n" +
	"\x04ping\x18\x02 \x01(\v2\x10.vmp.PingRequestH\x00R\x04ping\x123\n" +
	"\thost_info\x18\x03 \x01(\v2\x14.vmp.HostInfoRequestH\x00R\bhostInfo\x12&\n" +
	"\x04exec\x18\x04 \x01(\v2\x10.vmp.ExecRequestH\x00R\x04exec\x12<\n" +
	"\fupload_start\x18\x05 \x01(\v2\x17.vmp.UploadStartRequestH\x00R\vuploadStart\x12<\n" +
	"\fupload_chunk\x18\x06 \x01(\v2\x17.vmp.UploadChunkRequestH\x00R\vuploadChunk\x12?\n" +
	"\rupload_finish\x18\a \x01(\v2\x18.vmp.UploadFinishRequestH\x00R\fuploadFinishB\t\n" +
	"\acommand\"\xf1\x01\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12'\n" +
	"\x04ping\x18\x03 \x01(\v2\x11.vmp.PingResponseH\x00R\x04ping\x124\n" +
	"\thost_info\x18\x04 \x01(\v2\x15.vmp.HostInfoResponseH\x00R\bhostInfo\x12'\n" +
	"\x04exec\x18\x05 \x01(\v2\x11.vmp.ExecResponseH\x00R\x04exec\x12-\n" +
	"\x06upload\x18\x06 \x01(\v2\x13.vmp.UploadResponseH\x00R\x06uploadB\b\n" +
	"\x06result\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"\x11\n" +
	"\x0fHostInfoRequest\"P\n" +
	"\x10HostInfoResponse\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\"\xa2\x01\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\x12\x1c\n" +
	"\targuments\x18\x03 \x03(\tR\targuments\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x16\n" +
	"\x06detach\x18\x05 \x01(\bR\x06detach\"\x8a\x01\n" +
	"\fExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12\x1b\n" +
	"\ttimed_out\x18\x04 \x01(\bR\btimedOut\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\"h\n" +
	"\x12UploadStartRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256\"(\n" +
	"\x12UploadChunkRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x15\n" +
	"\x13UploadFinishRequest\"5\n" +
	"\x0eUploadResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x04R\fbytesWrittenB,Z*github.com/jimbersoftware/vex/internal/vmpb\x06proto3"

var (
	file_vmp_proto_rawDescOnce sync.Once
	file_vmp_proto_rawDescData []byte
)

func file_vmp_proto_rawDescGZIP() []byte {
	file_vmp_proto_rawDescOnce.Do(func() {
		file_vmp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vmp_proto_rawDesc), len(file_vmp_proto_rawDesc)))
	})
	return file_vmp_proto_rawDescData
}

var file_vmp_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_vmp_proto_goTypes = []any{
	(*Request)(nil),             // 0: vmp.Request
	(*Response)(nil),            // 1: vmp.Response
	(*PingRequest)(nil),         // 2: vmp.PingRequest
	(*PingResponse)(nil),        // 3: vmp.PingResponse
	(*HostInfoRequest)(nil),     // 4: vmp.HostInfoRequest
	(*HostInfoResponse)(nil),    // 5: vmp.HostInfoResponse
	(*ExecRequest)(nil),         // 6: vmp.ExecRequest
	(*ExecResponse)(nil),        // 7: vmp.ExecResponse
	(*UploadStartRequest)(nil),  // 8: vmp.UploadStartRequest
	(*UploadChunkRequest)(nil),  // 9: vmp.UploadChunkRequest
	(*UploadFinishRequest)(nil), // 10: vmp.UploadFinishRequest
	(*UploadResponse)(nil),      // 11: vmp.UploadResponse
}
var file_vmp_proto_depIdxs = []int32{
	2,  // 0: vmp.Request.ping:type_name -> vmp.PingRequest
	4,  // 1: vmp.Request.host_info:type_name -> vmp.HostInfoRequest
	6,  // 2: vmp.Request.exec:type_name -> vmp.ExecRequest
	8,  // 3: vmp.Request.upload_start:type_name -> vmp.UploadStartRequest
	9,  // 4: vmp.Request.upload_chunk:type_name -> vmp.UploadChunkRequest
	10, // 5: vmp.Request.upload_finish:type_name -> vmp.UploadFinishRequest
	3,  // 6: vmp.Response.ping:type_name -> vmp.PingResponse
	5,  // 7: vmp.Response.host_info:type_name -> vmp.HostInfoResponse
	7,  // 8: vmp.Response.exec:type_name -> vmp.ExecResponse
	11, // 9: vmp.Response.upload:type_name -> vmp.UploadResponse
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_vmp_proto_init() }
func file_vmp_proto_init() {
	if File_vmp_proto != nil {
		return
	}
	file_vmp_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Ping)(nil),
		(*Request_HostInfo)(nil),
		(*Request_Exec)(nil),
		(*Request_UploadStart)(nil),
		(*Request_UploadChunk)(nil),
		(*Request_UploadFinish)(nil),
	}
	file_vmp_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_Ping)(nil),
		(*Response_HostInfo)(nil),
		(*Response_Exec)(nil),
		(*Response_Upload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vmp_proto_rawDesc), len(file_vmp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vmp_proto_goTypes,
		DependencyIndexes: file_vmp_proto_depIdxs,
		MessageInfos:      file_vmp_proto_msgTypes,
	}.Build()
	File_vmp_proto = out.File
	file_vmp_proto_goTypes = nil
	file_vmp_proto_depIdxs = nil
}
